.github/workflows/stale.yml

- Future consideration to tighten this up to 14 days.

#65 Add github stale issues action for 30 days

---

.github/ISSUE_TEMPLATE/invitation.md

It implements the changes suggested in [#118 on the `EddieJaoudeCommunity.github.io` repo](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/118)
By opening an invitation issue at https://github.com/Vyvy-vi/Vyvy-vi 
(I tested it there 🙂 , since issues aren't present on forks)
I always saw the `#github` channel in the discord, getting filled with messages that contained the text that we wanted the new member to read, and rather doesn't reflect a personalised message from the user(who might be new to github). Thus, commenting out the text seems to improve the function it serves:
1- the user can read it
2- adding field columns might boost interaction(many invites seem dry, when they just include the default message)
3- A link to the server and a field to enter …

docs: Edited the Invitation template

---

.github/ISSUE_TEMPLATE/invitation.md

closes #505 
Enables all Invitation Issues to have the label 'invite me to the organisation'.
By creating an invitation issue.

fix: Changed Invite label

---

README.md

closes #469 
Removes the all-contributors badge since GitHub shows the list itself, and it doesn't work anyways.
Removal of redundancy. Task is completed.
By reading the README.md
https://github.com/EddieJaoudeCommunity/support/issues/469
Screenshots are available at the issue.
Shall we add one other badge? Something that depicts how many member the Discord Server has?

Fix: Issue #469

---

.github/ISSUE_TEMPLATE/invitation.md
.github/workflows/action.yml

automates organisation invitation and removed assignes in ISSUE_TEMPLATE on `invitation.md`
**NOTE:** create a repository secret called `ACCESS_TOKEN` and as a value provide a GitHub [personal access token](https://github.com/settings/tokens) with the scope of _`admin:org`_

Automate organisation invite

---

discord-readme.md

closes #1079 
removed Chilling section, cloud and chatting channels, moved heathfitness channel to text channels and renamed livestream to youtube.
update the discord's readme

remove deleted channels from discord's README

---

.github/ISSUE_TEMPLATE/opensource-review.md

closes #1179 
The label for the Issue Template for OSS Project Review was wrong (it didn't exist). This PR fixes that 🤓

Use the right label on OSS Project Review template

---

.github/ISSUE_TEMPLATE/portfolio-review.md

closes 3/4
Adds Live Stream Label to Portfolio Review
https://github.com/EddieHubCommunity/support/issues/1325

Updates Issue Template Label

---

.github/ISSUE_TEMPLATE/gh-profile-review.md

closes: 1/4 #1325
Adds Livestream Label to Github Profile Review
https://github.com/EddieHubCommunity/support/issues/1325

Added Labels for Issue Template

---

README.md

think it would be a good thing to add a link to the "Invite me to the Github Organization" issue

docs: add link to invitation issue

---

.github/ISSUE_TEMPLATE/bug.md

Update discord server invite link in the file .github/ISSUE_TEMPLATE/bug.md from https://discord.com/invite/jZQs6Wu to http://discord.eddiehub.org
closes #1401
Discord Invite link updated
https://github.com/EddieHubCommunity/support/issues/1401

Updated Discord Invitation link in bud.md

---

discord-readme.md

This pull request adds a section that has a simple guide on how to ask questions to make it easier on everyone to understand the question, problem or blocker that someone is facing.
Reviewing the steps and accepting that it is clear.
The change should be reflected in [discord-readme.md](https://github.com/EddieHubCommunity/support/blob/main/discord-readme.md).
I liked the way this guide was explained in Scrimba community. After I took permission from them, I added it here with some modifications.
not yet available
There are some things that we might need to change like the point **4. Share your code**. I think that we need to edit it based on what our bots would accept from the users based on their role, right? Or maybe we should enforce using GitHub repositories, gists …

feat: Add "Ask for help guide" to Discord ReadMe

---

.github/workflows/stale.yml

This pull request modifies the stalebot configuration to ignore issues with the `live stream review` label. Due to the fact that we are currently backlogged on these, we should not be closing them automatically.
This is a CRON task. If manual testing is desired, I can add the `workflow_dispatch` trigger.
Three issues came up in my notifications this evening where Stalebot was trying to close live stream review issues.
n/a

fix(tools): ignore livestream review

---

.github/workflows/community.yml

Now github actions won't run on any other org/user than ours
Limit the github action to only run on the main repository but not forks
All of this is taken from the github documentation:
- [Workflow Syntax](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [Context and Expression Syntax](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions)
This is a issue from a lot time fixed in this PR

fix: github action runs on forks

---

.github/ISSUE_TEMPLATE/invitation.yml

closes #2074
Makes Additional Context in the invitation template necessary
Change from `false` to `true` at https://github.com/EddieHubCommunity/support/blob/main/.github/ISSUE_TEMPLATE/invitation.yml#L26
Cross-checking with GitHub Issue template syntax
> I think we should make Additional Context obligatory because this would enable the community to know the actual reason why people are getting into EddieHub and would encourage us to work more on that. It would also enable the community members to know the newly joined folks better.
> 
> --- @Sam-Varghese 
resolves #2074

fix: EddieHubCommunity/support#2074

---

.github/ISSUE_TEMPLATE/other.yml

- Add a Markdown message in the `Other` template.
- This is for people to see the Discord invitation easier. This is also in all the other issue templates.
None.
This can be seen by going to my [fork](https://github.com/Panquesito7/support/blob/add_discord_invitation/.github/ISSUE_TEMPLATE/other.yml) of this repository. 🙂
Nope.
None.

fix: Add a Markdown message in the `Other` template

---

tips/githubtips.md

To avoid pull request conflicts, it's highly advisable to sync the fork with the upstream. Contributors would be able to merge safely.
Synchronizing the fork and the upstream of the original REPO

Updating githubtips.md : Sync the fork

---

docs/youtube/generic.md

- Use HTTPS instead in `youtube/generic.md`.
Nope.
AFAIK, no.
None.

fix: Use HTTPS instead in `youtube/generic.md`

---

docs/tips/git.md

- Add a tip for squashing the latest commit only.
- I think we might want to promote more these tips or add a link to them on our website: they're very useful. 🙂
I don't think this applies here unless we want to test the `git commit --amend` command. 😄
Nope.
Not that I know any.
None yet.

docs: add tip for squashing latest commit only

---

docs/discord/roles.md

- Remove the helper role.
- The helper role has been removed from the Discord server.
Nope.
AFAIK, nope.
None.

docs: remove the helper role

---

docs/discord/discord-readme.md

fix: removed tech channels

---

docs/discord/discord-readme.md

Resolves issue #8671
- pointed to "Browse Channels" menu option and explained what it offers
- text channels improvements, channels listed based on Discord's template flow
- added missing channels and it's descriptions
- removed "hackatons" channels
- moved bot-chat channel to "community discussions" section
- bonus content, introduced voice channel explanation
Sync pull request and review it locally.
#8669 
#8671
- bonus content, feel free to disregard, if you feel not fitting:
https://github.com/EddieHubCommunity/support/commit/bbe57a7a1823115ca773e219243e1e342ba20a6b

docs: #8671 Discord channel readme improvements
