- .github/ISSUE_TEMPLATE/community-question.md
This is my first pull request, I updated the community-question issue template
> Updated community-question issue template

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/general-question.md
- .github/ISSUE_TEMPLATE/review-my-open-source-link.md
- .github/ISSUE_TEMPLATE/technical-question.md
> Updated issue template with discord link

- README.md
closes #50 
I've added discord badge to the readme
> Add Discord Badge to Readme

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/community-question.md
- .github/ISSUE_TEMPLATE/general-question.md
- .github/ISSUE_TEMPLATE/review-my-open-source-link.md
- .github/ISSUE_TEMPLATE/technical-question.md
> Fixed typo on Issue templates

- README.md
Signed-off-by: abiola farounbi <farounbiabiola@gmail.com>
>  Changes made to the readMe file

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/community-question.md
- .github/ISSUE_TEMPLATE/general-question.md
- .github/ISSUE_TEMPLATE/review-my-open-source-link.md
- .github/ISSUE_TEMPLATE/technical-question.md
closes #136 
Correct Typo in Issue Templates
Corrected the typos in the Issue template files
> Correct Typo in Issue Templates

- README.md
Added some questions to a FAQ section.
Issue: https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/7
> docs(faq): add FAQ section to README

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/community-question.md
- .github/ISSUE_TEMPLATE/general-question.md
- .github/ISSUE_TEMPLATE/review-my-open-source-link.md
- .github/ISSUE_TEMPLATE/technical-question.md
- README.md
closes #3 
Update README.md file with Discussions
Showcase of Open source portfolios for feedback
> Update README.md with Discussions

- .github/ISSUE_TEMPLATE/invitation.md
closes #201 
Invitation Issue template
- adds correct issue label
- assigns to Eddie 
- how to make it public on their GitHub profile
- gives some tips on contributing to open source
> feat(template): invitation template #201

- README.md
> feat(contributors): removing all contributors #218

- README.md
closes #230 
Adds Instructions to set organization to public
> docs(readme): FAQ - Organisation to public #230

- README.md
closes #236
Adds a response to a frequent question which is "How do I get started with open source".
> docs(faq): add How do I get started with open source

- Finding-Open-Source-Projects.md
- README.md
closes #293
Add a question to the FAQ to help new members of the community find a project to contribute to.
N/A
N/A
- I provided an example of a tweet where we can find projects to contribute to. Let me know if it's not a good example or we should remove the example for that tip.
- The filename can be renamed after, I followed the spinal-case convention (more info [here](https://arcticicestudio.github.io/styleguide-markdown/rules/naming-conventions.html#file-naming))
#293
N/A
> docs(faq): add Finding Open Source Projects

- README.md
closes #388 
Add links to issue and discussion in README
> Add links to issue and discussion in README

- .github/ISSUE_TEMPLATE/invitation.md
- README.md
closes #427 
Updates the spelling from organisation to organization.
> docs: update organisation to organization

- tips/git.md
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
Creates a `tips` folder and adds a `git.md` file for git-related tips.
(I'm actually not sure what goes here...)
Read it! 😁 
- Confirm that the commands are correct and work as intended
- Definitions are clear and accurate
- Steps can be followed in an actual project.
Came from a discussion with @eddiejaoude and @Vyvy-vi on the Discord server.
There isn't one. 🙂
> Create git tips

- tips/git.md
> feat: glossary bullet to list

- README.md
> Fix: Redid a list of platforms for better readability

- .github/ISSUE_TEMPLATE/bug.md
closes #468
adds a description to the Bug-template.
NA
Yes, by copying the template to some test repo or at https://github.com/Vyvy-vi/Vyvy-vi/issues/new
It would be better to have a description for this.
(might erase confusion while raising issues regarding the repo, rather than questions about the community)
https://github.com/EddieJaoudeCommunity/support/issues/468
Can this be better phrased?
> DOCS: added description for bug template

- .github/ISSUE_TEMPLATE/invitation.md
- README.md
closes #522
1. Add a question mark to the third FAQ question.
2. Update the step ii instruction in the third FAQ question.
3. Add a red circle to the image below the third FAQ question’s step ii instruction.
Task is completed.
By reading the README.md
none
#522
Screenshots are available at the issue.
> Fix: Issue #522

- README.md
closes #541 
This PR addresses two things:
- The bullet points of the sub-lists
- Minor grammar corrections
> [FIX] Bullet Points

- README.md
closes #540
To have a more coherent style in the images.
Task is completed.
By reading the README.md
none
#540
> update FAQ - question 3's image

- CONTRIBUTING.md
closes #565 
Adds contributing documentation
> docs: contributing.md #565

- .github/workflows/invitation.yml
> Updated invitation.yml

- .github/workflows/community.yml
Modifies the github-actions bot's message to say "Thank you for raising an issue" instead of "Feel free to raise an issue" - seems weird to have the bot saying I'm welcome to raise an issue on the issue I just raised. 🤓 
If manual testing is requested, I can load this into an actions-testing repository I have and demonstrate functionality there.
Ref: [Discord Discussion](https://discord.com/channels/699608417039286293/738541096098988072/802582510721695744)
n/a
> tools: modify verbiage on message

- .github/ISSUE_TEMPLATE/resume-review.md
> Resume Review template

- .github/workflows/invitation.yml
> feat: Update organisation name in GH Actions

- discord-readme.md
> feat: renamed to EddieHub

- .github/workflows/community.yml
Change GitHub Action from `EddieJaoudeCommunity` to `EddieHubCommunity`
> Change GitHub Action to use EddieHubCommunity

- .github/ISSUE_TEMPLATE/general-question.md
Updated the template with a new name i.e EddieHub
> updated the file with new name i.e EddieHub

- discord-readme.md
> Fix typo mistake: achievements

- Finding-Open-Source-Projects.md
- README.md
closes #961
Replace old community link to new
> Fixing some links

- .github/workflows/community.yml
closes #853
Replace `!` with `...und...`
> Change GitHub Action Texts

- tips/glossary.md
closes #557 
Add glossary.md
- Add glossary.md file to the tips Folder
- Add an Example to glossary.md File
We descuss this on discord and github in this [issue](https://github.com/EddieHubCommunity/support/issues/557)
Is this good as my first real contributon to open source 🥺?
> docs: add glossary.md

- discord-readme.md
Changes made to the welcome message and added good-first-issues channel to README
To make the required changes in the README of discord
> Changes made in README

- .github/ISSUE_TEMPLATE/gh-profile-review.md
It adds the GitHub profile review issue template to review it on Livestream
> Added gh-profile-review-md

- README.md
closes #1200 
Allows new members of the community to raise an invitation Issue by clicking a link in the `README.md` in the FAQ section.
> feat: Update README.md link to raise invite Issue

- .github/ISSUE_TEMPLATE/opensource-review.md
Related to #1179 
Create an addition Issue Template
By creating the related issues
Useful for differentiating during a live stream.
https://github.com/EddieHubCommunity/support/issues/1179
> Created Open Source Review template

- .github/ISSUE_TEMPLATE/portfolio-review.md
This TEMPLATE can be used to provide Portfolio links for review by Eddie on a livestream.
It added a new ISSUE TEMPLATE for Portfolio review.
This PR is done based on a issue tagged for enhancement.
https://github.com/EddieHubCommunity/support/issues/1179
If possible please give me feedback on this pull request. :)
> Added a new ISSUE TEMPLATE for Portfolio Review

- discord-readme.md
I'll try to updated some descriptions that seems to be outdated and in my opinion, need to be changed. 
I have a question for the #organisation channel. It seems like the description unlikely describe the channel wisely. Personally, I get confused about it. Please consider to updated the descriptions.
> Updated some descriptions for some channels

- .github/ISSUE_TEMPLATE/opensource-review.md
Added live stream review label
closes 2/4
Added live stream review label.
https://github.com/EddieHubCommunity/support/issues/1325
> Update Labels in Issue Templates

- .github/ISSUE_TEMPLATE/resume-review.md
closes 4/4
Added 'live stream review' label.
#1325
> Added Labels for Issue Template 

- .github/ISSUE_TEMPLATE/gh-profile-review.md
- .github/ISSUE_TEMPLATE/opensource-review.md
- .github/ISSUE_TEMPLATE/resume-review.md
- README.md
closes #ISSUE-NO 
Updates Eddiehub Discord link in README
```diff
- https://discord.gg/jZQs6Wu
+ (http://discord.eddiehub.org/
```
By clicking the link in the README
Eddiehub discord link was changed on two different lines in the README file. 
#1401
> Update EddieHub Discord link in README

- .github/ISSUE_TEMPLATE/invitation.md
Fixes Grammer Issues In The Invitation Issue Template
> Fix Issue Template Grammer

- .github/ISSUE_TEMPLATE/invitation.md
closes #1667 
replaced the outdated links with the current links in the `invite to the organisation template`
> update outdated links

- .github/ISSUE_TEMPLATE/gh-profile-review.md
- .github/ISSUE_TEMPLATE/opensource-review.md
- .github/ISSUE_TEMPLATE/portfolio-review.md
- .github/ISSUE_TEMPLATE/resume-review.md
Fixes Grammar in issue template of gh-profile-review
> Fix Grammar Issue

- youtube/reviews.md
> docs: fix space issues and update issue type

- CODE_OF_CONDUCT.md
- discord-readme.md
closes #1833 
Resolved typo and grammatical error in discord-readme.md and CODE_OF_CONDUCT.md file 
https://github.com/EddieHubCommunity/support/issues/1833#issue-917084666
> Docs error fix

- .github/ISSUE_TEMPLATE/invitation.yml
> feat: update issue template (#1929)

- README.md
> Fixed broken invitation link in the README

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/gh-profile-review.md
- .github/ISSUE_TEMPLATE/ideas.md
- .github/ISSUE_TEMPLATE/invitation.yml
- .github/ISSUE_TEMPLATE/opensource-review.md
- .github/ISSUE_TEMPLATE/portfolio-review.md
- .github/ISSUE_TEMPLATE/resume-review.md
- .github/pull_request_template.md
- Improves wording (for example, `Github` -> `GitHub`) and converts some additional information in issue templates to comments.
None.
Hmm, I don't think this applies here, hehe. 😅
No, I don't think any additional context should be added.
None.
None yet.
> [feat/fix]: Minor wording and general improvements in the issue and PR templates

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/ideas.yml
This PR is addressing the following issue #2027
https://github.com/EddieHubCommunity/support/issues/2027
> Change type of screenshots from input to textarea

- README.md
resolve #2042
Broken Link issue fixed.
> Updated README.md with the correct link.

- tips/OpenSourceResources.md
- tips/OpenSourceTips.md
- tips/githubtips.md
closes #2056 
I have added awesome tips
pls let me know If I want to change any file name if it is not appropriate
> added more tips

- tips/OpenSourceResources.md
- tips/OpenSourceTips.md
- tips/finding-open-source-projects.md
- tips/git.md
- tips/githubtips.md
- tips/glossary.md
- Markdown and spelling improvements.
- Probably other things I don't know how to explain 😅 but shown in the Git diff.
None yet.
No.
https://github.com/EddieHubCommunity/support/issues/2056
None yet.
> [feat/fix] Minor improvements in the tips

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/other.yml
- Disables blank issues.
- IMO, they should be removed as we already provide a lot of templates.
None yet.
This can be tested by merging the PR and trying to create a blank issue. If it doesn't work, we can revert this PR.
No.
#2026
> feat: Disable blank issues

- youtube/reviews.md
- Improves the YouTube `review.md` file.
- Removed Markdown stuff such as headers. Other minor improvements are shown in the Git diff.
None.
Nope.
#2202
None.
> [feat/fix]: Minor improvements in the YouTube description file

- README.md
- Capitalize `d` in the `Discord` word in `README.md`.
None.
Nope.
Nope.
None.
> fix: Capitalize `d` in the `Discord` word in `README.md`

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/gh-profile-review.yml
- .github/ISSUE_TEMPLATE/ideas.yml
- .github/ISSUE_TEMPLATE/invitation.yml
- .github/ISSUE_TEMPLATE/opensource-review.yml
- .github/ISSUE_TEMPLATE/portfolio-review.yml
- .github/ISSUE_TEMPLATE/resume-review.yml
- Improve the issue templates.
None.
This would have to be merged to `master` to see if it works properly, or we can check the templates in my [fork](https://github.com/Panquesito7/support/tree/improve_issue_templates/.github/ISSUE_TEMPLATE). 🙂
Nope.
#2026, #2002, #1952, 
None.
> [feat/fix]: Improve the issue templates

- discord-readme.md
> Update discord-readme.md removed 42 line 

- LICENSE
- Update copyright holder's name to `EddieHub`
None.
No.
As far as I know, nope.
None.
> fix: Update copyright holder's name to `EddieHub`

- .github/workflows/community.yml
> fix: remove statistics workflow

- tips/glossary.md
Defining frequently used terms
Adding to the glossary the most frequently used terms that all contributors should be familiar with.
> Updating glossary.md adding frequently used terms

- discord-readme.md
emphasize on enhancing the layout of the discord channels.
> enhance the layout

- discord/discord-readme.md
- discord/roles.md
- mee6/welcome-dm.md
- tips/OpenSourceResources.md
- tips/githubtips.md
- tips/glossary.md
- Fix many Markdown linter issues in various files.
Nope.
None.
> fix: many Markdown linter issues in various files

- CODE_OF_CONDUCT.md
related to issue resolve #3004 
Hey 👋🏻
I have updated the email as requested!
Please review and merge! Thanks!
> [OTHER] Update COC Email

- docs/discord/discord-readme.md
> docs(discord-rules): follow discord comm guidelines

- README.md
Resolve #3349
Hey! @eddiejaoude 
&nbsp;&nbsp;&nbsp; I have come across a few grammatical errors in community support `README.md`. I am listing them in below bullet points. Please review this issue.
- The unfortunate thing about this is that it lacks a write-up on what was used. It's important to know the articles that were used for reference **~purpose~ purposes**.
- We could then have folks **~to~** have their own "support" repository and be able to PR in their contributions!
- Some examples would **~be:~ be -** Netflix, Facebook **~and~ ,and** of course EddieHub. Learn more on GitHub docs.
- Enter your username in the highlighted **~searchbar~ search bar:**
- Subscribe **~our~ to our** YouTube channel here
Thanks
> fix: README.md grammar

- CONTRIBUTING.md
Adds information about how maintainers are chosen in Eddiehub
Moderator discussion
> docs: add maintainer info to contributing.md

- docs/snippets/en/issue-before-pr.md
Issues come before PRs. PRs don't come before PRs. 🙃
> fix: open a pr before a pr?

- docs/snippets/en/screenshots.md
> docs: add full stops at the end

- docs/snippets/de/github-action-failing.md
- docs/snippets/de/issue-before-pr.md
- docs/snippets/de/join-discord.md
- docs/snippets/de/screenshots.md
- docs/snippets/de/smaller-pull-requests.md
- docs/snippets/de/update-branch.md
- docs/snippets/en/smaller-pull-requests.md
I could not find an issue to be closed by this. I am sorry if I have overseen it.
closes #3774 
I translated md files from English to German
For now, I translated it kind of formally (like, "you" in Sir, and not "you" like a "friend". The English version does not seem that formal. I can change this any time to casual as well.
Should I do the same in Japanese? Of course, I would have my translation reviewed by my Japanese Tandem Partner 😄
> Translate doc snippets md files from en to de

- docs/snippets/es/github-action-failing.md
- docs/snippets/es/issue-before-pr.md
- docs/snippets/es/join-discord.md
- docs/snippets/es/screenshots.md
- docs/snippets/es/smaller-pull-requests.md
- docs/snippets/es/update-branch.md
> Add folder ES with ES translations

- CODE_OF_CONDUCT.md
closes #3665  
This PR changes the email address in the CODE_OF_CONDUCT.md file, to the link http://eddiejaoude.io/contact
Yes, issue #3665
> Change Code of Conduct's email address to link

- docs/snippets/id/github-action-failing.md
- docs/snippets/id/issue-before-pr.md
- docs/snippets/id/join-discord.md
- docs/snippets/id/screenshots.md
- docs/snippets/id/smaller-pull-requests.md
- docs/snippets/id/update-branch.md
Closes #3828
- Add Indonesian translation for the snippet docs.
#3828
> Translate snippet docs to Indonesian

- .github/ISSUE_TEMPLATE/delete-api-user.yml
> Add Opt-Out Template

- .github/ISSUE_TEMPLATE/delete-api-user.yml
> fix: unique name for delete template

- README.md
closes #4044
- Removes confusing information
- Ensures tabs are converted to spaces instead of mismatched space/tabs.
- Markdown Fix/Prettier linting
- Removes some HTML for an <a> link to Markdown format.
Open in GitPod and look at the README.
I wrote most of the stuff that doesn't make sense.
I moved the socials to the top next to the "active chatters" for better conversion to join discord and subscribe to Eddie's YT channel
Existing README:
---
> Remove old and outdated information from the README and make it more presentable.

- .github/ISSUE_TEMPLATE/add-api-user.yml
> fix: unique name for add template

- .github/ISSUE_TEMPLATE/twitter-review.yml
Issue template for LIVE stream for Twitter profile reviews
> feat: twitter review issue template

- docs/discord/discord-readme.md
Removing old discord channels referenced in `discord-readme.md`
Ensure all `#good-first-issues` and `#opensource` are no longer in doc.
New member and was reading your docs. This lead me to find deleted channels remaining to confuse me and hopefully avoid that for others.
N/A
> docs: removing outdated channels no longer used

- docs/snippets/README.md
Unfortunately Sema is no longer available, but we can still use the templates with GitHub "Saved Replies"
> docs: official docs for saved replies

- .github/ISSUE_TEMPLATE/portfolio-review.yml
Context: Live stream https://www.youtube.com/watch?v=jWqMuVKU53c
> docs: add github repo link field

- docs/discord/roles.md
Added period and added description in roles as requested.
> Added period, description sorted errors.

- docs/discord/discord-readme.md
Removed deleted channels, ALERTS section (no publicly available channels), added/removed punctuation where necessary, fixed discord-readme.md link (old URL directed to 404 page), added viewable emojis
> docs(discord-readme): improved content

- docs/_layout/sidebar.md
- docs/youtube/livestream.md
closes #3612
The links of the options mentioned in the sidebar.md file was not working. Now it will work.
> Fixed BUG 3612 

- docs/tips/OpenSourceResources.md
- Fix outdated Hacktobefest link.
Not sure if this applies here.
Nope.
None.
> fix: outdated Hacktobefest link

- .github/ISSUE_TEMPLATE/biodrop-review.yml
Update the label and template from linkfree review to BioDrop Review
> fix: biodrop-review.yml
